### ISSUE TITLE
Interview view page wasn't loading for me (edge case, working for now)

### ISSUE THREAD

**Issue by pritpaul** [tbpmig/mig-website#173] opened 2015-01-29 20:36 UTC
The short version is probably that it gets stuck in a redirect loop when nobody is logged in (for some level of logged in), more details below:

I went to tbp.engin.umich.edu and clicked the Undergrad Electee Interviews (Actives) event.  After a few seconds Firefox gave me an error:

>The page isn't redirecting properly
>
>Firefox has detected that the server is redirecting the request for this address in a way that will never complete.
>
>    This problem can sometimes be caused by disabling or refusing to accept cookies."

I exported the cookies and tried with wget:
>    [pmahal@centos ~]$ wget --load-cookies=/mntc/Downloads/cookies.txt https://tbp.engin.umich.edu/calendar/event/378/
>    --2015-01-29 15:21:52--  https://tbp.engin.umich.edu/calendar/event/378/
>    Resolving tbp.engin.umich.edu... 141.213.15.170
    Connecting to tbp.engin.umich.edu|141.213.15.170|:443... connected.
    HTTP request sent, awaiting response... 302 FOUND
    Location: https://tbp.engin.umich.edu/calendar/interview_view_actives/378/ [following]
    --2015-01-29 15:21:53--  https://tbp.engin.umich.edu/calendar/interview_view_actives/378/
    Reusing existing connection to tbp.engin.umich.edu:443.
    HTTP request sent, awaiting response... 302 FOUND
    Location: https://tbp.engin.umich.edu/calendar/event/378/ [following]
    --2015-01-29 15:21:53--  https://tbp.engin.umich.edu/calendar/event/378/
    Reusing existing connection to tbp.engin.umich.edu:443.
    HTTP request sent, awaiting response... 302 FOUND
    Location: https://tbp.engin.umich.edu/calendar/interview_view_actives/378/ [following]
    --2015-01-29 15:21:53--  https://tbp.engin.umich.edu/calendar/interview_view_actives/378/
    Reusing existing connection to tbp.engin.umich.edu:443.
    HTTP request sent, awaiting response... 302 FOUND
    Location: https://tbp.engin.umich.edu/calendar/event/378/ [following]
    --2015-01-29 15:21:53--  https://tbp.engin.umich.edu/calendar/event/378/
    Reusing existing connection to tbp.engin.umich.edu:443.
    HTTP request sent, awaiting response... 302 FOUND
    Location: https://tbp.engin.umich.edu/calendar/interview_view_actives/378/ [following]
    --2015-01-29 15:21:53--  https://tbp.engin.umich.edu/calendar/interview_view_actives/378/
    Reusing existing connection to tbp.engin.umich.edu:443.
    HTTP request sent, awaiting response... ^C

After this, while trying to find the bug-reporting page, I went to tbp.engin.umich.edu again and got the "you're not logged in" banner (I don't recall seeing it before).  I clicked log in, it switched to having me logged in (without taking me through the weblogin screen), and then the event page worked.

I just had an inspiration and fully logged out and clicked the event page and get the same redirect loop error from firefox.  Hence the summary above.  I can provide relevant cookies if you're interested in actually tracking down the "half-logged-in" state (my gut feeling is that's probably not worth it and if/when we want to fix it just breaking the loop when logged out is fine)

**Comment by mrealm** [comment] 2015-01-29 20:45
This happened to me as well a few weeks ago. I was unable to reproduce and thus didn't file a bug. However, this does appear to be limited to the Firefox browser. Using Chrome / Safari this didn't happen.

**Comment by pritpaul** [comment] 2015-01-29 20:53
So not having looked through the code at all (disclaimer), here's my speculation (now that i've noticed that the not logged in banner is an error banner for trying to access the interview page, so I probably wasn't logged in to the tbp site at least the first time through):

- (logged-out) User goes to event/378 page
- event/378 page send browser redirect to interview_view_actives/378 page
- interview_view_actives/378 page sees no user is logged in, appends that error banner to the session or whatever, and tells browser to go "Back"
- browsers interpret this differently, with firefox (and IE) going back one redirect to event/378 and others going back to the last page the user was successfully on (main site or whatever)

**Comment by mikehand** [comment] 2015-01-29 21:00
Close enough. The generic event page was logging that you had successfully
landed there before checking if it should redirect to interviews. It now
will do that check after. This should be fixed with the next update. If the
problem persists, we can re-open

Mike Hand

**Closed** 2015-01-29 21:01 UTC
