### ISSUE TITLE
Event list page shows Unsign-up button for events I am not signed up for

### ISSUE THREAD

**Issue by pritpaul** [tbpmig/mig-website#212] opened 2016-04-05 16:30 UTC
https://tbp.engin.umich.edu/calendar/event_list/

Several events that I am not signed up for show me an "Unsign-up" button.  The events affected seem to change sometimes when I refresh.  I believe the attendee count on the page for those events includes me.  When I click through to the event page (by clicking the event title), I am not listed under attendees and the total count is different than it was on the event list page.

Right now this is happening for:
- Fifth General (count on event page is 1 greater than list page)
- MRelay Dinner/Mixer (count on event page is 2 fewer than list page)
- Engineering MRelay (count on event page is 1 fewer than list page)
- New Initiatives IV (count on event page is 1 greater than list page)

I think I was previously seeing an Unsign-up button for Leslie Science Center as well, but that disappeared on a refresh.

None of these events show up on the My Events page or in the Events signed up for section on the Track My Progress page.

I just tried clicking the Unsign-up button for 2 of these (and left the rest alone for investigation).
- For Fifth General, clicking grays for a second but the button comes right back
- For MRelay Dinner/Mixer, clicking actually changed it to a "Sign-up" button, but refreshing the event list page brought the "Unsign-up" button right back.  I still don't show as signed up on the actual event.

**Comment by mikehand** [comment] 2016-04-05 16:33
This is a known existing bug. It's caused by Ajax issues we've not been
able to isolate that are present in events open to non-members. It likely
means someone has been making events public that shouldn't be. Closing as
duplicate

On Tuesday, April 5, 2016, pritpaul <notifications@github.com> wrote:

> https://tbp.engin.umich.edu/calendar/event_list/
>
> Several events that I am not signed up for show me an "Unsign-up" button.
> The events affected seem to change sometimes when I refresh. I believe the
> attendee count on the page for those events includes me. When I click
> through to the event page (by clicking the event title), I am not listed
> under attendees and the total count is different than it was on the event
> list page.
>
> Right now this is happening for:
>
>    - Fifth General (count on event page is 1 greater than list page)
>    - MRelay Dinner/Mixer (count on event page is 2 fewer than list page)
>    - Engineering MRelay (count on event page is 1 fewer than list page)
>    - New Initiatives IV (count on event page is 1 greater than list page)
>
> I think I was previously seeing an Unsign-up button for Leslie Science
> Center as well, but that disappeared on a refresh.
>
> None of these events show up on the My Events page or in the Events signed
> up for section on the Track My Progress page.
>
> I just tried clicking the Unsign-up button for 2 of these (and left the
> rest alone for investigation).
>
>    - For Fifth General, clicking grays for a second but the button comes
>    right back
>    - For MRelay Dinner/Mixer, clicking actually changed it to a "Sign-up"
>    button, but refreshing the event list page brought the "Unsign-up" button
>    right back. I still don't show as signed up on the actual event.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/tbpmig/mig-website/issues/212>
>


-- 
Mike Hand

**Closed** 2016-04-05 16:34 UTC

**Comment by pritpaul** [comment] 2016-04-05 16:41
Dupe of #185 to be specific (hope you don't mind the extra comment, just thought it might be useful in the future)
